---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: BlueXPのコピーと同期に関するサポートは、フォーラム、チャットサービス、ビデオなど、さまざまなリソースで入手できます。 
---
= BlueXPのコピーと同期に関するテクニカルFAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== はじめに

以下の質問は、BlueXPのコピーと同期の開始に関するものです。



=== BlueXPのコピーと同期の仕組み

BlueXPのコピーと同期は、ネットアップのデータブローカーソフトウェアを使用してソースからターゲットにデータを同期します（これは_sync relationship_と呼ばれます）。

データブローカーグループは、ソースとターゲットの同期関係を制御します。同期関係を設定すると、BlueXPのコピーと同期によってソースシステムが分析され、複数のレプリケーションストリームに分割されて、選択したターゲットデータにプッシュされます。

最初のコピーの後、設定したスケジュールに基づいて変更されたデータが同期されます。



=== 14 日間の無料トライアルはどのように機能しますか？

14日間の無償トライアルは、BlueXPのコピーと同期サービスに登録すると開始されます。14日間にわたって作成したBlueXPのコピーおよび同期関係については、ネットアップが料金を請求することはありません。ただし、導入するデータブローカーのすべてのリソース料金は引き続き適用されます。



=== BlueXPのコピーと同期の料金はいくらですか？

BlueXPのコピーと同期の使用に関連するコストには、サービス料金とリソース料金の2種類があります。

* サービス料金 *

従量課金制の場合、BlueXPのコピー/同期サービスは、作成する同期関係の数に基づいて時間単位で料金が発生します。

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS で従量課金制の価格を確認できます"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS の年間価格を確認します"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure で価格を表示します"^]


BlueXPのコピーライセンスと同期ライセンスは、ネットアップの担当者からも入手できます。各ライセンスでは、 12 カ月間で 20 の同期関係が有効になります。

link:concept-licensing.html["ライセンスの詳細については、こちらをご覧ください。"]。


NOTE: Cloud Volumes Service とAzure NetApp Files では、BlueXPのコピー関係と同期関係を無料で利用できます。

* リソース料金 *

リソース料金は、クラウドでデータブローカーを実行するためのコンピューティングコストとストレージコストに関連しています。



=== BlueXPのコピーと同期の請求方法とサブスクリプションの管理方法を教えてください。

14 日間の無料トライアル終了後に、同期関係の料金を支払う方法は 2 通りあります。最初のオプションは、 AWS または Azure から購読することです。 AWS または Azure を使用すると、従量課金制または年払いが可能になります。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。いずれの場合も、サブスクリプションはプロバイダのマーケットプレイスを通じて管理され、BlueXPのコピーと同期のユーザインターフェイスでは*管理されません。



=== BlueXPのコピーと同期をクラウド外で使用できますか？

BlueXPのコピーと同期は、非クラウドアーキテクチャで使用できます。ソースとターゲットはオンプレミスに配置できるため、データブローカーソフトウェアを使用することもできます。

BlueXPのクラウド外でのコピーと同期の使用については、次の点に注意してください。

* データブローカーグループがBlueXPのコピーおよび同期サービスと通信するには、インターネット接続が必要です。
* ネットアップからライセンスを直接購入しない場合は、PAYGO BlueXPのコピーおよび同期サービスの請求にAWSまたはAzureのアカウントが必要になります。




=== BlueXPのコピーと同期へのアクセス方法を教えてください。

BlueXPのコピーと同期は、BlueXP Webサイトの*[Sync]*タブから実行できます。



=== データブローカーグループとは

各データブローカーは、データブローカーグループに属しています。データブローカーをグループ化すると、同期関係のパフォーマンスが向上します。



== サポートされているソースとターゲット

同期関係でサポートされているソースとターゲットに関連する次の質問。



=== BlueXPのコピーと同期はどのソースとターゲットに対応していますか？

BlueXPのコピーと同期は、さまざまな種類の同期関係に対応しています。 link:reference-supported-relationships.html["リスト全体を表示します。"]。



=== BlueXPのコピーと同期では、NFSとSMBのどのバージョンがサポートされていますか？

BlueXPのコピーと同期では、NFSバージョン3以降とSMBバージョン1以降がサポートされます。

link:reference-requirements.html["同期の要件の詳細については、こちらをご覧ください。"]。



=== Amazon S3 がターゲットである場合、特定の S3 ストレージクラスにデータを階層化できますか。

はい。 AWS S3 がターゲットである場合は、特定の S3 ストレージクラスを選択できます。

* 標準（これがデフォルトクラス）
* インテリジェント階層化
* 標準的なアクセス頻度は低い
* 1 回のアクセスではほとんど発生しません
* Glacier Deep Archive
* Glacierの柔軟な取得
* Glacier のインスタント検索




=== Azure BLOB ストレージのストレージ階層について教えてください。

BLOB コンテナがターゲットの場合は、特定の Azure BLOB ストレージ階層を選択できます。

* ホットストレージ
* 優れたストレージ




=== Google Cloud のストレージ階層をサポートしていますか？

はい。 Google Cloud Storage バケットがターゲットの場合は、特定のストレージクラスを選択できます。

* 標準
* ニアライン
* コールドライン（ Coldline ）
* Archive サービスの略




== ネットワーキング

ここでは、BlueXPのコピーと同期のネットワーク要件について説明します。



=== BlueXPのコピーと同期のネットワーク要件を教えてください。

BlueXPのコピーおよび同期環境では、選択したプロトコルまたはオブジェクトストレージAPI（Amazon S3、Azure Blob、IBM Cloud Object Storage）を使用してデータブローカーグループをソースとターゲットに接続する必要があります。

さらに、データブローカーグループがBlueXPのコピーおよび同期サービスと通信し、他のいくつかのサービスやリポジトリに接続できるように、ポート443経由のアウトバウンドインターネット接続が必要です。

詳細： link:reference-networking.html["ネットワーク要件を確認します。"]。



=== データブローカーでプロキシサーバを使用できますか。

はい。

BlueXPのコピーと同期は、ベーシック認証の有無にかかわらずプロキシサーバに対応しています。データブローカーの導入時にプロキシサーバを指定した場合、データブローカーからの HTTP および HTTPS トラフィックはすべてプロキシ経由でルーティングされます。NFS や SMB などの HTTP 以外のトラフィックは、プロキシサーバー経由でルーティングできないことに注意してください。

プロキシサーバの唯一の制限は、 NFS または Azure NetApp Files 同期関係で転送中のデータ暗号化を使用する場合です。暗号化されたデータは HTTPS 経由で送信され、プロキシサーバー経由でルーティングすることはできません。



== データの同期

次の質問は、データ同期の仕組みに関連しています。



=== 同期はどのくらいの頻度で行われますか。

デフォルトのスケジュールは、毎日の同期に設定されています。初期同期化の後、次の操作を実行できます。

* 同期スケジュールを、希望する日数、時間数、分数に変更します
* 同期スケジュールを無効にします
* 同期スケジュールを削除します（データは失われません。同期関係のみが削除されます）。




=== 最小同期スケジュールは何ですか？

データを 1 分ごとに同期するように関係をスケジュールできます。



=== データブローカーグループは、ファイルの同期に失敗したときに再試行しますか。またはタイムアウトしますか？

データブローカーグループは、 1 つのファイルの転送が失敗してもタイムアウトしません。代わりに、データブローカーグループは、ファイルをスキップする前に 3 回再試行します。再試行値は、同期関係の設定で設定できます。

link:task-managing-relationships.html#changing-the-settings-for-a-sync-relationship["同期関係の設定を変更する方法について説明します。"]。



=== 非常に大規模なデータセットがある場合はどうすればよいですか。

1 つのディレクトリに 60 万以上のファイルが含まれている場合は、データブローカーグループを設定してペイロードを処理できるように、 mailto ： ng-cloudsync-support@netapp.com [ お問い合わせ ] をご利用ください。データブローカーグループにメモリを追加しなければならない場合があります。

マウントポイント内のファイルの総数に制限はありません。上位ディレクトリやサブディレクトリの階層のレベルに関係なく、 600 、 000 以上のファイルを含む大規模なディレクトリには、追加のメモリが必要です。



== セキュリティ

セキュリティに関する次の質問



=== BlueXPのコピーと同期は安全ですか？

はい。BlueXPのコピーサービスと同期サービスのネットワーク接続は、すべてを使用して行います https://aws.amazon.com/sqs/["Amazon Simple Queue Service （ SQS ）"^]。

データブローカーグループと Amazon S3 、 Azure Blob 、 Google Cloud Storage 、 IBM Cloud Object Storage の間の通信は、すべて HTTPS プロトコルを使用して行われます。

BlueXPのコピーと同期をオンプレミス（ソースまたはデスティネーション）システムと使用する場合は、次の接続オプションを推奨します。

* AWS Direct Connect 、 Azure ExpressRoute 、または Google Cloud Interconnect 接続。インターネット経由ではない（指定したクラウドネットワークとのみ通信可能）
* オンプレミスゲートウェイデバイスとクラウドネットワーク間の VPN 接続
* S3 バケット、 Azure BLOB ストレージ、または Google クラウドストレージを使用した安全なデータ転送のために、 Amazon Private S3 エンドポイント、 Azure Virtual Network サービスエンドポイント、またはプライベート Google アクセスを確立できます。


いずれの方法でも、オンプレミスのNASサーバとBlueXPのコピーおよび同期データブローカーグループの間にセキュアな接続を確立できます。



=== BlueXPのコピーと同期によってデータが暗号化されていますか？

* BlueXPのコピーと同期は、ソースとターゲットのNFSサーバ間の転送中データの暗号化に対応しています。 link:task-nfs-encryption.html["詳細はこちら。"]。
* SMBについては、BlueXPのコピーと同期でサーバ側で暗号化したSMB 3.0と3.11のデータがサポートされます。BlueXPのコピーと同期では、暗号化されたデータがソースからターゲットにコピーされ、ターゲットではデータが暗号化されたままになります。
+
BlueXPのコピーと同期では、SMBデータ自体は暗号化できません。

* Amazon S3 バケットが同期関係のターゲットである場合は、 AWS KMS の暗号化と AES-256 暗号化を使用してデータ暗号化を有効にするかどうかを選択できます。
* Google Storageバケットが同期関係のターゲットである場合は、デフォルトのGoogle管理暗号化キーを使用するか、独自のKMSキーを使用するかを選択できます。




== 権限

次の質問は、データ権限に関連しています。



=== SMB データの権限はターゲットの場所に同期されていますか？

BlueXPのコピーと同期を設定して、ソースのSMB共有とターゲットのSMB共有の間、およびソースのSMB共有からオブジェクトストレージ（ONTAP S3を除く）へのアクセス制御リスト（ACL）を保持できます。


NOTE: BlueXPのコピーと同期では、オブジェクトストレージからSMB共有へのACLのコピーはサポートされていません。

link:task-copying-acls.html["SMB 共有間で ACL をコピーする方法について説明します。"]。



=== NFS データの権限はターゲットの場所に同期されていますか。

BlueXPのコピーと同期では、次のようにNFSサーバ間でNFS権限が自動的にコピーされます。

* NFSバージョン3：BlueXPのコピーと同期で権限とユーザグループの所有者がコピーされます。
* NFSバージョン4：BlueXPのACLのコピーと同期でコピー




== オブジェクトストレージのメタデータ



=== オブジェクトストレージのメタデータを保持する同期関係はどのようなものですか？

BlueXPのコピーと同期では、次のタイプの同期関係のオブジェクトストレージメタデータがソースからターゲットにコピーされます。

* Amazon S3 -> Amazon S3 ^1
* Amazon S3 -> StorageGRID
* StorageGRID -> Amazon S3
* StorageGRID -> StorageGRID の順にクリックします
* StorageGRID -> Google Cloud Storage
* Google Cloud Storage -> StorageGRID ^1
* Google Cloud Storage -> IBM Cloud Object Storage ^1
* Google Cloud Storage -> Amazon S3 ^1
* Amazon S3 -> Google Cloud Storage
* IBM Cloud Object Storage -> Google Cloud Storage
* StorageGRID -> IBM クラウドオブジェクトストレージ
* IBM Cloud Object Storage -> StorageGRID の順にクリックします
* IBM Cloud Object Storage -> IBM Cloud Object Storage


^1 この同期関係には、以下が必要です link:task-creating-relationships.html["同期関係を作成するときに、[オブジェクトのコピー]設定を有効にします"]。



=== NFSまたはSMBがソースである同期中にレプリケートされるメタデータの種類

ユーザID、更新日時、アクセス時間、GIDなどのメタデータはデフォルトでレプリケートされます。ユーザは、同期関係の作成時にACLを必須としてマークすることで、CIFSからACLをレプリケートすることを選択できます。



== パフォーマンス

BlueXPのコピーと同期のパフォーマンスに関する質問を次に示します。



=== 同期関係の進行状況インジケータは何を表していますか。

同期関係は、データブローカーグループのネットワークアダプタのスループットを示しています。複数のデータブローカーを使用して同期パフォーマンスを高速化した場合、スループットはすべてのトラフィックの合計になります。このスループットは 20 秒ごとに更新されます。



=== パフォーマンスの問題が発生しています。同時転送の数を制限できますか。

大容量のファイル（それぞれ複数の TiB ）がある場合は、転送プロセスが完了するまでに時間がかかることがあり、パフォーマンスに影響する可能性があります。

同時転送の数を制限すると効果的です。mailto ： ng-cloudsync-support@netapp.com [ お問い合わせ ]



=== Azure NetApp Files でパフォーマンスが低いのはなぜですか？

Azure NetApp Files との間でデータを同期する際、ディスクのサービスレベルが Standard の場合は障害やパフォーマンスの問題が発生することがあります。

同期パフォーマンスを向上させるには、サービスレベルを Premium または Ultra に変更します。

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Azure NetApp Files のサービスレベルとスループットの詳細については、こちらをご覧ください"^]。



=== Cloud Volumes Service for AWS でパフォーマンスが低下するのはなぜですか。

クラウドボリュームとの間でデータを同期する場合、クラウドボリュームのパフォーマンスレベルが標準の場合は、障害やパフォーマンスの問題が発生することがあります。

サービスレベルを Premium または Extreme に変更して、同期のパフォーマンスを向上させます。



=== 1 つのグループに必要なデータブローカーの数

新しい関係を作成する場合は、 1 つのデータブローカーを 1 つのグループで開始します（アクセラレーション同期関係に属する既存のデータブローカーを選択した場合を除く）。多くの場合、 1 つのデータブローカーで同期関係のパフォーマンス要件を満たすことができます。同期されていない場合は、データブローカーをグループに追加することで、同期パフォーマンスを高速化できます。ただし、まず、同期のパフォーマンスに影響を与える可能性のある他の要因を確認する必要があります。

データ転送のパフォーマンスには、複数の要因が影響します。全体的な同期パフォーマンスは、ネットワーク帯域幅、レイテンシ、ネットワークトポロジ、データブローカー VM の仕様、ストレージシステムのパフォーマンスによって影響を受ける可能性があります。たとえば、グループ内の単一のデータブローカーが 100MB/s に達することはありますが、ターゲットのディスクスループットでは 64MB/s しか許可されませんその結果、データブローカーグループはデータのコピーを試行し続けますが、ターゲットではデータブローカーグループのパフォーマンスを達成できません。

そのため、ネットワークのパフォーマンスとターゲットのディスクスループットを確認してください。

次に、グループにデータブローカーを追加してその関係の負荷を共有することで、同期パフォーマンスを高速化することを検討します。 link:task-managing-relationships.html#accelerating-sync-performance["同期のパフォーマンスを高速化する方法について説明します。"]。



== 項目を削除する

次の質問は、ソースとターゲットから同期関係とデータを削除することに関連しています。



=== BlueXPのコピーと同期関係を削除するとどうなりますか？

関係を削除すると、以降のすべてのデータの同期が停止し、支払いが終了します。ターゲットに同期されたデータはそのまま残ります。



=== ソースサーバから何かを削除するとどうなりますか。ターゲットからも削除されていますか？

デフォルトでは、 Active Sync 関係がある場合、ソースサーバ上で削除されたアイテムは、次回の同期時にターゲットから削除されません。ただし、関係ごとの同期設定にはオプションがあり、BlueXPのコピーと同期でターゲットの場所にあるファイルがソースから削除された場合に削除されるように定義できます。

link:task-managing-relationships.html#changing-the-settings-for-a-sync-relationship["同期関係の設定を変更する方法について説明します。"]。



=== ターゲットから何かを削除するとどうなりますか？ソースからも削除されていますか？

ターゲットから削除されたアイテムは、ソースから削除されません。ソースからターゲットへの関係は一方向です。次回の同期サイクルでは、BlueXPのコピーと同期によってソースとターゲットが比較され、アイテムが見つからないことが特定され、BlueXPのコピーと同期によってソースからターゲットにもう一度コピーされます。



== トラブルシューティング

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["ネットアップナレッジベース：BlueXP copy and sync FAQ：Support and Troubleshooting"^]



== データブローカーのディープダイブ

次の質問は、データブローカーに関連しています。



=== データブローカーのアーキテクチャについて説明できますか？

確かに。最も重要なポイントは次のとおりです。

* データブローカーは、 Linux ホスト上で実行されている Node.js アプリケーションです。
* BlueXPのコピーと同期は、次のようにデータブローカーを導入します。
+
** AWS ： AWS Cloudformation テンプレートから
** Azure ： Azure Resource Manager から
** Google ： Google Cloud Deployment Manager から
** 独自の Linux ホストを使用する場合は、ソフトウェアを手動でインストールする必要があります


* データブローカーソフトウェアは、自動的に最新バージョンにアップグレードします。
* データブローカーは、 AWS SQS を信頼性の高い安全な通信チャネルとして使用し、制御と監視を行います。SQS は永続性レイヤも提供します。
* データブローカーをグループに追加することで、転送速度を向上させ、高可用性を追加することができます。1 つのデータブローカーに障害が発生した場合、サービスの耐障害性があります

