---
settings:
  name: BlueXP copy and sync
  harmony_integration: maestro
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXPのコピーと同期のドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 制限
      url: "/reference-limitations.html"
  - title: はじめに
    entries:
    - title: BlueXPのコピーと同期について説明します
      url: "/concept-cloud-sync.html"
    - title: クイックスタート
      url: "/task-quick-start.html"
    - title: サポートされている同期関係を表示する
      url: "/reference-supported-relationships.html"
    - title: ソースとターゲットを準備します
      url: "/reference-requirements.html"
    - title: ネットワークを準備
      url: "/reference-networking.html"
    - title: データブローカーをインストール
      entries:
      - title: AWS にインストールします
        url: "/task-installing-aws.html"
      - title: Azure にインストール
        url: "/task-installing-azure.html"
      - title: Google Cloud にインストールします
        url: "/task-installing-gcp.html"
      - title: Linux ホストにをインストールします
        url: "/task-installing-linux.html"
  - title: BlueXPのコピーと同期を使用
    entries:
    - title: ソースとターゲットの間でデータを同期します
      entries:
      - title: 同期関係を作成します
        url: "/task-creating-relationships.html"
      - title: SMB 共有から ACL をコピーする
        url: "/task-copying-acls.html"
      - title: 転送中の NFS データを暗号化
        url: "/task-nfs-encryption.html"
      - title: 橋本からの秘密を使用してください
        url: "/task-external-vault.html"
    - title: ライセンスをセットアップする
      url: "/task-licensing.html"
    - title: 同期関係を管理します
      url: "/task-managing-relationships.html"
    - title: データブローカーの管理
      url: "/task-managing-data-brokers.html"
    - title: レポートを表示して、設定を調整します
      url: "/task-managing-reports.html"
    - title: データブローカーをアンインストール
      url: "/task-uninstalling.html"
  - title: REST API で自動化
    url: "/api-sync.html"
  - title: 概念
    entries:
    - title: ライセンス
      url: "/concept-licensing.html"
    - title: データのプライバシー
      url: "/concept-privacy.html"
    - title: よく寄せられる質問
      url: "/faq.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: BlueXPのコピーと同期の概要
      url: concept-cloud-sync.html
    - title: クイックスタート
      url: task-quick-start.html
    - title: よく寄せられる質問
      url: faq.html
  - title: BlueXPのコピーと同期を使用
    links:
    - title: 同期関係を作成します
      url: task-creating-relationships.html
    - title: ライセンスをセットアップする
      url: task-licensing.html
    - title: データブローカーグループの管理
      url: task-managing-data-brokers.html
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXPブログ
      url: https://cloud.netapp.com/blog
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: BlueXPのすべてのマニュアル
