---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 14 日間の無料トライアル終了後に、同期関係の料金を支払う方法は 2 通りあります。最初のオプションは従量課金制です。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。 
---
= 無償トライアルの終了後に同期関係の料金を支払う
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
14 日間の無料トライアル終了後に、同期関係の料金を支払う方法は 2 通りあります。最初のオプションは、 AWS または Azure から従量課金制または年払いのいずれかを購読することです。2 つ目の選択肢は、ネットアップから直接ライセンスを購入することです。

AWS Marketplace または Azure Marketplace からサブスクライブできます。両方から購読することはできません。

Marketplace サブスクリプションを使用して、ネットアップからライセンスを使用することもできます。たとえば、 25 の同期関係がある場合は、ライセンスを使用して最初の 20 の同期関係に料金を支払い、残りの 5 つの同期関係を持つ AWS または Azure から従量課金制で支払うことができます。

link:concept-licensing.html["ライセンスの仕組みについては、こちらをご覧ください。"]。

無償トライアルの終了後すぐに支払いを行わないと、追加の関係を作成することはできません。既存の関係は削除されませんが、ライセンスを登録または入力するまでは変更を加えることはできません。

ライセンスの管理には、BlueXPのコピーと同期、または該当するWebサイトを使用する必要があります。デジタルウォレットを使用することはできません*。



== [[AWS]] AWSからサブスクライブ

AWS を使用すると、従量課金制または年払いが可能です。

.従量課金制の手順
. BlueXP  のナビゲーションメニューから、*モビリティ>コピーと同期*を選択します。
. [ライセンス]*を選択します。
. 「* AWS *」を選択します。
. [サブスクライブ]*を選択し、*[続行]*を選択します。
. AWS Marketplaceから登録し、BlueXPのコピー&同期サービスに再度ログインして登録を完了します。
+
次のビデオは、プロセスを示しています。

+
.AWS MarketplaceからのBlueXP  コピーと同期の配信登録
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.年間の支払い手順
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS Marketplace ページに移動します。"^]。
. [*購読を続行する*]を選択します。
. 契約オプションを選択し、*契約の作成*を選択します。




== [[Azure]Azureからサブスクライブ

Azure では、従量課金制または年間の支払いが可能です。

.必要なもの
関連するサブスクリプションの投稿者または所有者権限を持つ Azure ユーザーアカウント。

.手順
. BlueXP  のナビゲーションメニューから、*モビリティ>コピーと同期*を選択します。
. [ライセンス]*を選択します。
. 「 * Azure * 」を選択します。
. [サブスクライブ]*を選択し、*[続行]*を選択します。
. Azureポータルで、*[作成]*を選択し、オプションを選択して*[サブスクライブ]*を選択します。
+
「毎月 * 」を選択すると、時間単位で支払います。または、「毎年」を選択すると、前払いした 1 年分の料金が支払われます。

. 導入が完了したら、通知ポップアップでSaaSリソースの名前を選択します。
. BlueXPのコピーと同期に戻るには、[アカウントの設定]*を選択します。
+
次のビデオは、プロセスを示しています。

+
.Azure MarketplaceでBlueXP  のコピーと同期をサブスクライブ
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenses] NetAppからライセンスを購入し、BlueXP  コピーと同期に追加する

同期関係の料金を事前に支払うには、1つ以上のライセンスを購入してBlueXPのコピーおよび同期サービスに追加する必要があります。

.必要なもの
ライセンスのシリアル番号、およびライセンスが関連付けられているネットアップサポートサイトのアカウントのユーザ名とパスワードが必要です。

.手順
. mailto ： ng-cloudsync-contact@netapp.com ？ subject= Cloud %20Sync%20Service%20-%20BYOL %20License%20Purchase%20Request までにライセンスを購入してください。 [Contacting NetApp] 。
. BlueXP  のナビゲーションメニューから、*モビリティ>コピーと同期*を選択します。
. [ライセンス]*を選択します。
. [ライセンスの追加]*を選択し、必要な情報を追加します。
+
.. シリアル番号を入力します。
.. 追加するライセンスに関連付けられているネットアップサポートサイトのアカウントを選択します。
+
*** アカウントがBlueXPにすでに追加されている場合は、ドロップダウンリストから選択します。
*** アカウントがまだ追加されていない場合は、*[Add NSS Credentials]*を選択し、ユーザ名とパスワードを入力して*[Register]*を選択し、ドロップダウンリストから選択します。


.. 「 * 追加」を選択します。






== ライセンスを更新します

ネットアップから購入したBlueXPのコピーと同期のライセンスを延長した場合、BlueXPのコピーと同期で新しい有効期限が自動的に更新されません。有効期限を更新するには、ライセンスを再度追加する必要があります。ライセンスの管理には、BlueXPのコピーと同期、または該当するWebサイトを使用する必要があります。デジタルウォレットを使用することはできません*。

.手順
. BlueXP  のナビゲーションメニューから、*モビリティ>コピーと同期*を選択します。
. [ライセンス]*を選択します。
. [ライセンスの追加]*を選択し、必要な情報を追加します。
+
.. シリアル番号を入力します。
.. 追加するライセンスに関連付けられているネットアップサポートサイトのアカウントを選択します。
.. 「 * 追加」を選択します。




.結果
BlueXPのコピーと同期により、既存のライセンスが新しい有効期限に更新されます。
